version: '3'

services:
  container:
      build: ./
      image: debian_for_local_usage:latest
      container_name: "homework_03_${USERNAME}"
      volumes:
        - ./local:/etc/nginx
        - ./${USERNAME}_files:/home/${USERNAME}
      tty: true
      ports:
        - 9090:8080
